<a href="https://colab.research.google.com/github/Priyamchamp/ANN-labs/blob/main/Ann_5(updated).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

# Get the number of input vectors and their lengths from the user
num_vectors = int(input("Enter the number of input vectors: "))
vector_length = int(input("Enter the length of each vector: "))

# Initialize the input matrices
X = np.zeros((num_vectors, vector_length))
Y = np.zeros((num_vectors, vector_length))

# Get input for X and Y matrices
for i in range(num_vectors):
    print(f"Enter values for input vector X[{i}]:")
    for j in range(vector_length):
        X[i, j] = int(input(f"Enter value for X[{i}, {j}]: "))

    print(f"Enter values for input vector Y[{i}]:")
    for j in range(vector_length):
        Y[i, j] = int(input(f"Enter value for Y[{i}, {j}]: "))

    # Calculate the weight matrix W
    W = np.dot(X.T, Y)

    # Define retrieval functions
    def retrieve_x(y):
        return np.dot(y, W.T)

    def retrieve_y(x):
        return np.dot(x, W)

    # Display the weight matrix W
    print("\nWeight matrix W:")
    print(W)

    # Test with the given pairs
    print("\nRetrieved X from Y:")
    for y in Y:
        x_retrieved = np.sign(retrieve_x(y))
        print(x_retrieved)

    print("\nRetrieved Y from X:")
    for x in X:
        y_retrieved = np.sign(retrieve_y(x))
        print(y_retrieved)


Enter the number of input vectors: 1
Enter the length of each vector: 3
Enter values for input vector X[0]:
Enter value for X[0, 0]: 1
Enter value for X[0, 1]: -1
Enter value for X[0, 2]: 1
Enter values for input vector Y[0]:
Enter value for Y[0, 0]: -1
Enter value for Y[0, 1]: 1
Enter value for Y[0, 2]: -1

Weight matrix W:
[[-1.  1. -1.]
 [ 1. -1.  1.]
 [-1.  1. -1.]]

Retrieved X from Y:
[ 1. -1.  1.]

Retrieved Y from X:
[-1.  1. -1.]
